version: '3.5'

services:
  proxy:
    restart: unless-stopped
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./.docker/data/nginx/certs:/etc/nginx/certs
      - ./.docker/data/nginx/dhparam:/etc/nginx/dhparam
    environment:
      - DHPARAM_GENERATION=false
    labels:
      - com.github.chrisb9.local_https.nginx_proxy

  companion:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.docker/data/letsencrypt:/etc/letsencrypt
      - ./.docker/data/nginx/certs:/etc/nginx/certs
    environment:
      - DNS_CLIENT=${DNS_CLIENT:?must be set}
      - HTTPS_MAIN_DOMAIN=${HTTPS_MAIN_DOMAIN:?must be set}
      - CUSTOM_LABEL=com.github.chrisb9.local_https.nginx_proxy
